// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzTwjguQm9I9Hlnrx3Y7pBCnxznzrgt0k',
    appId: '1:858771771649:web:6e3a4f14a0950228928b00',
    messagingSenderId: '858771771649',
    projectId: 'cylinderkini',
    authDomain: 'cylinderkini.firebaseapp.com',
    storageBucket: 'cylinderkini.appspot.com',
    measurementId: 'G-QEK1VQ9J5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUrzvZqK5XVrdZJSVA2KFRQo5L74CXFBM',
    appId: '1:858771771649:android:d6ce64fa469a59f1928b00',
    messagingSenderId: '858771771649',
    projectId: 'cylinderkini',
    storageBucket: 'cylinderkini.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxSW50HTptICHR_1o7Shi9DA3QaGCxa_s',
    appId: '1:858771771649:ios:f1aa350d8bad6d27928b00',
    messagingSenderId: '858771771649',
    projectId: 'cylinderkini',
    storageBucket: 'cylinderkini.appspot.com',
    iosBundleId: 'com.royalcourtbd.cylinderKini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxSW50HTptICHR_1o7Shi9DA3QaGCxa_s',
    appId: '1:858771771649:ios:48e1b5e929256303928b00',
    messagingSenderId: '858771771649',
    projectId: 'cylinderkini',
    storageBucket: 'cylinderkini.appspot.com',
    iosBundleId: 'com.royalcourtbd.cylinderKini.RunnerTests',
  );
}
